workspace = { members = ["examples/hash_example"] }
[profile.release]
lto = "thin"

[package]
name = "leancrypto"
version = "0.9.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = { version = "0.69.1", features = ["experimental"] }
