name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install meson
      run: sudo apt-get install -y meson
    - uses: actions/checkout@v3
    - name: configure
      run: meson setup build
    - name: make
      run: meson compile -C build
    - name: Test
      run: meson test -C build
