name: User space CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    - name: Install meson
      run: |
        brew update
        brew install meson
    - name: Meson setup
      run: meson setup build
    - name: Meson compile
      run: meson compile -C build
    - name: Meson test
      run: meson test -C build
