name: Linux user space CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install meson
      run: |
        sudo apt-get update
        sudo apt-get install -y meson gcovr
    - name: Meson setup
      run: meson setup build -Db_coverage=true
    - name: Meson compile
      run: meson compile -C build
    - name: Meson test
      run: meson test -C build
    - name: Generate test coverage report
      run: ninja coverage-html -C build
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: build/meson-logs/coveragereport
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: build/libleancrypto.so.*.gcno
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: false
        indicators: true
        output: both
        thresholds: '60 80'
