name: Windows user space CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: git meson mingw-w64-x86_64-meson
    - name: Meson setup
      run: msys2 -c 'CC=gcc meson setup build'
    - name: Meson compile
      run: msys2 -c 'meson compile -C build'
    - name: Meson test
      run: msys2 -c 'meson test -C build'
