name: Windows user space CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v4
    - name: Install meson
      run: pip3 install --user meson
    - name: Meson setup
      run: meson setup build
    - name: Meson compile
      run: meson compile -C build
    - name: Meson test
      run: meson test -C build
