name: Windows user space CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install meson
      run: python -m pip install meson
    - name: Meson setup
      run: meson setup build
    - name: Meson compile
      run: meson compile -C build
    - name: Meson test
      run: meson test -C build
